spring.application.name=Pulsora
server.port=8080
spring.datasource.url=jdbc:postgresql://db:5432/pulsora_db
spring.datasource.username=X
spring.datasource.password=X
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false


spring.mail.host=smtp.ethereal.email
spring.mail.port=587
spring.mail.username=X.email
spring.mail.password=X
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.debug=true


server.error.include-binding-errors=always
server.error.include-message=always

logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping=TRACE
logging.level.org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter=TRACE
logging.level.com.projects.Pulsora=DEBUG

# Gemini API
gemini.api.key=X
gemini.api.url=https://generativelanguage.googleapis.com/v1/models/gemini-2.5-flash-lite:generateContent


# External APIs
usgs.api.url=https://earthquake.usgs.gov/earthquakes/feed/v1.0/summary/all_hour.geojson
gdacs.api.url=https://www.gdacs.org/gdacsapi/api/events/geteventlist
nasa.api.url=https://eonet.gsfc.nasa.gov/api/v3/events
openweather.api.url=https://api.openweathermap.org/data/3.0/onecall
openweather.api.key=X
