package com.projects.Pulsora.AutomatedTrigger.Fetcher;

import com.projects.Pulsora.AutomatedTrigger.Dto.ExEventDto;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Service;
import org.springframework.web.client.RestTemplate;

import java.util.*;

@Service
@Slf4j
public class GDACSFetcher {

    @Value("${gdacs.api.url}")
    private String apiUrl;

    private final RestTemplate restTemplate = new RestTemplate();

    public List<ExEventDto> fetch() {
        List<ExEventDto> events = new ArrayList<>();

        try {
            Map<String, Object> response = restTemplate.getForObject(apiUrl, Map.class);
            if (response == null || !response.containsKey("features")) {
                log.warn("GDACS response invalid or empty");
                return events;
            }

            List<Map<String, Object>> features = (List<Map<String, Object>>) response.get("features");

            for (Map<String, Object> feature : features) {
                try {
                    Map<String, Object> props = (Map<String, Object>) feature.get("properties");
                    Map<String, Object> geometry = (Map<String, Object>) feature.get("geometry");

                    List<Double> coords = (List<Double>) geometry.get("coordinates");
                    if (coords == null || coords.size() < 2) continue;

                    double lon = coords.get(0);
                    double lat = coords.get(1);
                    String id = (String) feature.get("id");
                    String type = (String) props.getOrDefault("eventtype", "Disaster");
                    String country = (String) props.getOrDefault("country", "Unknown");
                    double mag = props.get("severityvalue") != null ? ((Number) props.get("severityvalue")).doubleValue() : 0.0;
                    String severity = props.getOrDefault("alertlevel", "LOW").toString().toUpperCase();

                    events.add(ExEventDto.builder()
                            .externalId("GDACS_" + id)
                            .eventType(type)
                            .location(country)
                            .magnitude(mag)
                            .severity(severity)
                            .latitude(lat)
                            .longitude(lon)
                            .autoGenerated(true)
                            .build());
                } catch (Exception e) {
                    log.error("Error parsing GDACS event: {}", e.getMessage());
                }
            }

            log.info("DACSFetcher fetched {} global disasters.", events.size());
        } catch (Exception e) {
            log.error("Failed to fetch from GDACS: {}", e.getMessage());
        }

        return events;
    }
}
