package com.projects.Pulsora.AutomatedTrigger.Fetcher;

import com.projects.Pulsora.AutomatedTrigger.Dto.ExEventDto;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Service;
import org.springframework.web.client.RestTemplate;

import java.util.*;

@Service
@Slf4j
public class NASADataFetcher {

    @Value("${nasa.api.url}")
    private String apiUrl;

    private final RestTemplate restTemplate = new RestTemplate();

    public List<ExEventDto> fetch() {
        List<ExEventDto> events = new ArrayList<>();

        try {
            Map<String, Object> response = restTemplate.getForObject(apiUrl + "?category=wildfires&status=open", Map.class);
            if (response == null || !response.containsKey("events")) {
                log.warn("⚠️ NASA EONET response invalid or empty");
                return events;
            }

            List<Map<String, Object>> eventList = (List<Map<String, Object>>) response.get("events");

            for (Map<String, Object> event : eventList) {
                try {
                    String id = (String) event.get("id");
                    String title = (String) event.get("title");
                    List<Map<String, Object>> geometries = (List<Map<String, Object>>) event.get("geometries");

                    if (geometries == null || geometries.isEmpty()) continue;

                    Map<String, Object> geometry = geometries.get(0);
                    List<Double> coords = (List<Double>) geometry.get("coordinates");

                    double lon = coords.get(0);
                    double lat = coords.get(1);

                    events.add(ExEventDto.builder()
                            .externalId("NASA_" + id)
                            .eventType("Wildfire")
                            .location(title)
                            .magnitude(0.0)
                            .severity("HIGH")
                            .latitude(lat)
                            .longitude(lon)
                            .autoGenerated(true)
                            .build());
                } catch (Exception e) {
                    log.error("❌ Error parsing NASA EONET event: {}", e.getMessage());
                }
            }

            log.info("✅ NASADataFetcher fetched {} wildfire events.", events.size());
        } catch (Exception e) {
            log.error("❌ Failed to fetch from NASA EONET: {}", e.getMessage());
        }

        return events;
    }
}
