package com.projects.Pulsora.AutomatedTrigger.Fetcher;

import com.projects.Pulsora.AutomatedTrigger.Dto.ExEventDto;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Service;
import org.springframework.web.client.RestTemplate;

import java.time.Instant;
import java.time.LocalDateTime;
import java.time.ZoneId;
import java.util.*;

@Service
@Slf4j
public class OpenWeatherFetcher {

    @Value("${openweather.api.url}")
    private String apiUrl;

    @Value("${openweather.api.key}")
    private String apiKey;

    private final RestTemplate restTemplate = new RestTemplate();

    public List<ExEventDto> fetch() {
        List<ExEventDto> events = new ArrayList<>();

        try {
            double lat = 28.6139;
            double lon = 77.2090;

            String url = String.format("%s?lat=%f&lon=%f&appid=%s&exclude=current,minutely,hourly,daily",
                    apiUrl, lat, lon, apiKey);

            Map<String, Object> response = restTemplate.getForObject(url, Map.class);

            if (response == null || !response.containsKey("alerts")) {
                log.info("ℹ️ No active weather alerts for location.");
                return events;
            }

            List<Map<String, Object>> alerts = (List<Map<String, Object>>) response.get("alerts");

            for (Map<String, Object> alert : alerts) {
                String event = (String) alert.getOrDefault("event", "Weather Alert");
                String sender = (String) alert.getOrDefault("sender_name", "Unknown");
                long start = alert.containsKey("start") ? ((Number) alert.get("start")).longValue() : System.currentTimeMillis();
                LocalDateTime eventTime = Instant.ofEpochSecond(start).atZone(ZoneId.systemDefault()).toLocalDateTime();

                String severity = event.toLowerCase().contains("storm") ? "HIGH"
                        : event.toLowerCase().contains("rain") ? "MEDIUM"
                        : "LOW";

                events.add(ExEventDto.builder()
                        .externalId("OWM_" + UUID.randomUUID())
                        .eventType(event)
                        .location("Delhi, India")
                        .magnitude(0.0)
                        .severity(severity)
                        .latitude(lat)
                        .longitude(lon)
                        .timeStamp(eventTime)
                        .autoGenerated(true)
                        .build());
            }

            log.info("✅ OpenWeatherFetcher fetched {} active weather alerts.", events.size());
        } catch (Exception e) {
            log.error("❌ Failed to fetch from OpenWeather: {}", e.getMessage());
        }

        return events;
    }
}
