package com.projects.Pulsora.AutomatedTrigger.Fetcher;

import com.projects.Pulsora.AutomatedTrigger.Dto.ExEventDto;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Service;
import org.springframework.web.client.RestTemplate;

import java.time.Instant;
import java.time.ZoneId;
import java.time.ZonedDateTime;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;

@Service
@Slf4j
public class USGSFetcher {

    @Value("${usgs.api.url}")
    private String apiUrl;

    private final RestTemplate restTemplate = new RestTemplate();

    public List<ExEventDto> fetch() {
        List<ExEventDto> events = new ArrayList<>();

        try {
            Map<String, Object> response = restTemplate.getForObject(apiUrl, Map.class);
            if (response == null || !response.containsKey("features")) {
                log.warn(" USGS response invalid or empty");
                return events;
            }

            List<Map<String, Object>> features = (List<Map<String, Object>>) response.get("features");

            for (Map<String, Object> feature : features) {
                try {
                    Map<String, Object> props = (Map<String, Object>) feature.get("properties");
                    Map<String, Object> geometry = (Map<String, Object>) feature.get("geometry");
                    List<Double> coordinates = (List<Double>) geometry.get("coordinates");

                    if (coordinates == null || coordinates.size() < 2) continue;

                    double lon = coordinates.get(0);
                    double lat = coordinates.get(1);
                    String id = (String) feature.get("id");
                    String place = (String) props.getOrDefault("place", "Unknown location");
                    double mag = props.get("mag") != null ? ((Number) props.get("mag")).doubleValue() : 0.0;
                    long timeMillis = ((Number) props.get("time")).longValue();

                    ZonedDateTime eventTime = Instant.ofEpochMilli(timeMillis).atZone(ZoneId.systemDefault());

                    String severity = mag >= 6.0 ? "HIGH" : mag >= 4.0 ? "MEDIUM" : "LOW";

                    events.add(ExEventDto.builder()
                            .externalId("USGS_" + id)
                            .eventType("Earthquake")
                            .location(place)
                            .magnitude(mag)
                            .severity(severity)
                            .latitude(lat)
                            .longitude(lon)
                            .timeStamp(eventTime.toLocalDateTime())
                            .autoGenerated(true)
                            .build());
                } catch (Exception e) {
                    log.error(" Error parsing USGS event: {}", e.getMessage());
                }
            }

            log.info(" USGSFetcher fetched {} earthquake events.", events.size());
        } catch (Exception e) {
            log.error(" Failed to fetch from USGS: {}", e.getMessage());
        }

        return events;
    }
}
