package com.projects.Pulsora.Entity;

import com.fasterxml.jackson.annotation.JsonIgnore;
import jakarta.persistence.*;
import lombok.Getter;
import lombok.Setter;

import java.time.LocalDateTime;
import java.util.List;

@Getter
@Setter
@Entity
@Table(name = "disaster_event")
public class DisasterEvent {

    public enum Severity {
        LOW, MEDIUM, HIGH
    }

    public enum Status {
        REPORTED, CONFIRMED, RESOLVED
    }

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(name = "event_type", length = 255)
    private String eventType;

    @Column(length = 255)
    private String location;

    private Double magnitude;

    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private Severity severity;

    @Column(name = "time_stamp", updatable = false)
    private LocalDateTime timeStamp;

    private Double latitude;
    private Double longitude;

    @Column(name = "api_source", length = 255)
    private String apiSource;

    @Column(name = "external_id", unique = true, length = 255)
    private String externalId;

    @Column(name = "auto_generated")
    private boolean autoGenerated = false;

    @OneToMany(mappedBy = "disasterEvent", cascade = CascadeType.ALL, orphanRemoval = true)
    @JsonIgnore
    private List<UserResponse> userResponses;

    @OneToMany(mappedBy = "disasterEvent", cascade = CascadeType.ALL, orphanRemoval = true)
    @JsonIgnore
    private List<AIResponse> aiResponses;

    @PrePersist
    protected void onCreate() {
        if (this.timeStamp == null) {
            this.timeStamp = LocalDateTime.now();
        }
    }
}
