package com.projects.Pulsora.AutomatedTrigger.Dto;

import lombok.*;
import java.time.LocalDateTime;

@Data
@AllArgsConstructor
@NoArgsConstructor
@Builder
public class ExEventDto {
    private String externalId;
    private String eventType;
    private String location;
    private Double magnitude;
    private String severity;
    private LocalDateTime timeStamp;
    private boolean autoGenerated;
    private Double latitude;
    private Double longitude;
}
